services:
  api:
    image: jwkaiser/lisse-api:latest
    container_name: lisse-api
    ports:
      - 8001:8001
    env_file:
      - .env.prod
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn build && yarn start"
    restart: unless-stopped
    networks:
      - koa-network

networks:
  koa-network:
    driver: bridge
